export type TZEntry = {
  label: string;
  sub: string;
  tz: string;
  keys: string[];
};

// Each entry: label (display), sub (secondary), tz (IANA), keys (extra search terms)
export const TZ_DATA: TZEntry[] = [
  // ── Abbreviations ─────────────────────────────────────────────────────────
  { label: "UTC / GMT", sub: "Coordinated Universal Time", tz: "UTC", keys: ["utc", "gmt", "coordinated universal"] },
  { label: "EST — Eastern Standard Time", sub: "North America", tz: "America/New_York", keys: ["est", "eastern standard"] },
  { label: "EDT — Eastern Daylight Time", sub: "North America", tz: "America/New_York", keys: ["edt", "eastern daylight", "eastern time", "et"] },
  { label: "CST — Central Standard Time", sub: "North America", tz: "America/Chicago", keys: ["cst", "central standard"] },
  { label: "CDT — Central Daylight Time", sub: "North America", tz: "America/Chicago", keys: ["cdt", "central daylight", "central time", "ct"] },
  { label: "MST — Mountain Standard Time", sub: "North America", tz: "America/Denver", keys: ["mst", "mountain standard"] },
  { label: "MDT — Mountain Daylight Time", sub: "North America", tz: "America/Denver", keys: ["mdt", "mountain daylight", "mountain time", "mt"] },
  { label: "PST — Pacific Standard Time", sub: "North America", tz: "America/Los_Angeles", keys: ["pst", "pacific standard"] },
  { label: "PDT — Pacific Daylight Time", sub: "North America", tz: "America/Los_Angeles", keys: ["pdt", "pacific daylight", "pacific time", "pt"] },
  { label: "AKST — Alaska Standard Time", sub: "Alaska, US", tz: "America/Anchorage", keys: ["akst", "akdt", "alaska"] },
  { label: "HST — Hawaii Standard Time", sub: "Hawaii, US", tz: "Pacific/Honolulu", keys: ["hst", "hdt", "hawaii", "honolulu"] },
  { label: "AST — Atlantic Standard Time", sub: "Canada / Caribbean", tz: "America/Halifax", keys: ["ast", "adt", "atlantic standard", "atlantic time"] },
  { label: "NST — Newfoundland Standard Time", sub: "Newfoundland, Canada", tz: "America/St_Johns", keys: ["nst", "ndt", "newfoundland"] },
  { label: "BRT — Brasília Time", sub: "Brazil", tz: "America/Sao_Paulo", keys: ["brt", "brst", "brasilia", "brasília"] },
  { label: "ART — Argentina Time", sub: "Argentina", tz: "America/Argentina/Buenos_Aires", keys: ["art", "argentina time"] },
  { label: "CLT — Chile Standard Time", sub: "Chile", tz: "America/Santiago", keys: ["clt", "clst", "chile time"] },
  { label: "COT — Colombia Time", sub: "Colombia", tz: "America/Bogota", keys: ["cot", "colombia time"] },
  { label: "PET — Peru Time", sub: "Peru", tz: "America/Lima", keys: ["pet", "peru time"] },
  { label: "VET — Venezuela Time", sub: "Venezuela", tz: "America/Caracas", keys: ["vet", "venezuela time"] },
  { label: "BST — British Summer Time", sub: "United Kingdom", tz: "Europe/London", keys: ["bst", "british summer"] },
  { label: "GMT — Greenwich Mean Time", sub: "United Kingdom", tz: "Europe/London", keys: ["gmt", "greenwich mean time"] },
  { label: "CET — Central European Time", sub: "Europe", tz: "Europe/Paris", keys: ["cet", "central european time"] },
  { label: "CEST — Central European Summer Time", sub: "Europe", tz: "Europe/Paris", keys: ["cest", "central european summer"] },
  { label: "EET — Eastern European Time", sub: "Eastern Europe", tz: "Europe/Athens", keys: ["eet", "eest", "eastern european"] },
  { label: "MSK — Moscow Standard Time", sub: "Russia", tz: "Europe/Moscow", keys: ["msk", "moscow time", "moscow standard"] },
  { label: "IST — India Standard Time", sub: "India", tz: "Asia/Kolkata", keys: ["ist", "india standard", "indian standard"] },
  { label: "PKT — Pakistan Standard Time", sub: "Pakistan", tz: "Asia/Karachi", keys: ["pkt", "pakistan standard"] },
  { label: "BST — Bangladesh Standard Time", sub: "Bangladesh", tz: "Asia/Dhaka", keys: ["bdt", "bangladesh standard"] },
  { label: "NPT — Nepal Time", sub: "Nepal", tz: "Asia/Kathmandu", keys: ["npt", "nepal time"] },
  { label: "ICT — Indochina Time", sub: "Thailand / Vietnam", tz: "Asia/Bangkok", keys: ["ict", "indochina time"] },
  { label: "WIB — Western Indonesia Time", sub: "Indonesia", tz: "Asia/Jakarta", keys: ["wib", "western indonesia"] },
  { label: "SGT — Singapore Time", sub: "Singapore / Malaysia", tz: "Asia/Singapore", keys: ["sgt", "singapore time"] },
  { label: "HKT — Hong Kong Time", sub: "Hong Kong", tz: "Asia/Hong_Kong", keys: ["hkt", "hong kong time"] },
  { label: "CST — China Standard Time", sub: "China", tz: "Asia/Shanghai", keys: ["china standard", "cst china"] },
  { label: "JST — Japan Standard Time", sub: "Japan", tz: "Asia/Tokyo", keys: ["jst", "japan standard"] },
  { label: "KST — Korea Standard Time", sub: "South Korea", tz: "Asia/Seoul", keys: ["kst", "korea standard"] },
  { label: "PHT — Philippine Time", sub: "Philippines", tz: "Asia/Manila", keys: ["pht", "philippine time"] },
  { label: "AEST — Australian Eastern Standard Time", sub: "New South Wales / Victoria", tz: "Australia/Sydney", keys: ["aest", "aedt", "australian eastern"] },
  { label: "ACST — Australian Central Standard Time", sub: "South Australia / NT", tz: "Australia/Darwin", keys: ["acst", "acdt", "australian central"] },
  { label: "AWST — Australian Western Standard Time", sub: "Western Australia", tz: "Australia/Perth", keys: ["awst", "australian western"] },
  { label: "NZST — New Zealand Standard Time", sub: "New Zealand", tz: "Pacific/Auckland", keys: ["nzst", "nzdt", "new zealand standard"] },
  { label: "WAT — West Africa Time", sub: "West Africa", tz: "Africa/Lagos", keys: ["wat", "west africa time"] },
  { label: "CAT — Central Africa Time", sub: "Central Africa", tz: "Africa/Harare", keys: ["cat", "central africa time"] },
  { label: "EAT — East Africa Time", sub: "East Africa", tz: "Africa/Nairobi", keys: ["eat", "east africa time"] },
  { label: "SAST — South Africa Standard Time", sub: "South Africa", tz: "Africa/Johannesburg", keys: ["sast", "south africa standard"] },
  { label: "GST — Gulf Standard Time", sub: "UAE / Oman", tz: "Asia/Dubai", keys: ["gst", "gulf standard"] },
  { label: "AST — Arabia Standard Time", sub: "Saudi Arabia / Qatar / Kuwait", tz: "Asia/Riyadh", keys: ["arabia standard"] },
  { label: "TRT — Turkey Time", sub: "Turkey", tz: "Europe/Istanbul", keys: ["trt", "turkey time"] },
  { label: "IRST — Iran Standard Time", sub: "Iran", tz: "Asia/Tehran", keys: ["irst", "irdt", "iran standard"] },

  // ── Countries ──────────────────────────────────────────────────────────────
  { label: "Afghanistan", sub: "Kabul", tz: "Asia/Kabul", keys: ["afghanistan", "kabul"] },
  { label: "Albania", sub: "Tirana", tz: "Europe/Tirane", keys: ["albania", "tirana"] },
  { label: "Algeria", sub: "Algiers", tz: "Africa/Algiers", keys: ["algeria", "algiers"] },
  { label: "Argentina", sub: "Buenos Aires", tz: "America/Argentina/Buenos_Aires", keys: ["argentina"] },
  { label: "Armenia", sub: "Yerevan", tz: "Asia/Yerevan", keys: ["armenia", "yerevan"] },
  { label: "Australia (Eastern)", sub: "Sydney / Melbourne / Brisbane", tz: "Australia/Sydney", keys: ["australia east", "australia eastern"] },
  { label: "Australia (Central)", sub: "Adelaide / Darwin", tz: "Australia/Adelaide", keys: ["australia central"] },
  { label: "Australia (Western)", sub: "Perth", tz: "Australia/Perth", keys: ["australia west", "australia western"] },
  { label: "Austria", sub: "Vienna", tz: "Europe/Vienna", keys: ["austria", "vienna"] },
  { label: "Azerbaijan", sub: "Baku", tz: "Asia/Baku", keys: ["azerbaijan", "baku"] },
  { label: "Bangladesh", sub: "Dhaka", tz: "Asia/Dhaka", keys: ["bangladesh", "dhaka"] },
  { label: "Belarus", sub: "Minsk", tz: "Europe/Minsk", keys: ["belarus", "minsk"] },
  { label: "Belgium", sub: "Brussels", tz: "Europe/Brussels", keys: ["belgium", "brussels"] },
  { label: "Bolivia", sub: "La Paz", tz: "America/La_Paz", keys: ["bolivia", "la paz"] },
  { label: "Brazil (East)", sub: "São Paulo / Rio de Janeiro", tz: "America/Sao_Paulo", keys: ["brazil", "brasil"] },
  { label: "Bulgaria", sub: "Sofia", tz: "Europe/Sofia", keys: ["bulgaria", "sofia"] },
  { label: "Cambodia", sub: "Phnom Penh", tz: "Asia/Phnom_Penh", keys: ["cambodia", "phnom penh"] },
  { label: "Canada (Eastern)", sub: "Toronto / Ottawa / Montreal", tz: "America/Toronto", keys: ["canada eastern", "canada east"] },
  { label: "Canada (Central)", sub: "Winnipeg / Regina", tz: "America/Winnipeg", keys: ["canada central"] },
  { label: "Canada (Mountain)", sub: "Calgary / Edmonton", tz: "America/Edmonton", keys: ["canada mountain"] },
  { label: "Canada (Pacific)", sub: "Vancouver", tz: "America/Vancouver", keys: ["canada pacific", "canada west"] },
  { label: "Chile", sub: "Santiago", tz: "America/Santiago", keys: ["chile", "santiago"] },
  { label: "China", sub: "Beijing / Shanghai", tz: "Asia/Shanghai", keys: ["china", "prc", "people's republic"] },
  { label: "Colombia", sub: "Bogotá", tz: "America/Bogota", keys: ["colombia", "bogota", "bogotá"] },
  { label: "Croatia", sub: "Zagreb", tz: "Europe/Zagreb", keys: ["croatia", "zagreb"] },
  { label: "Cuba", sub: "Havana", tz: "America/Havana", keys: ["cuba", "havana"] },
  { label: "Czech Republic", sub: "Prague", tz: "Europe/Prague", keys: ["czech", "czechia", "prague"] },
  { label: "Denmark", sub: "Copenhagen", tz: "Europe/Copenhagen", keys: ["denmark", "copenhagen"] },
  { label: "Ecuador", sub: "Quito", tz: "America/Guayaquil", keys: ["ecuador", "quito"] },
  { label: "Egypt", sub: "Cairo", tz: "Africa/Cairo", keys: ["egypt", "cairo"] },
  { label: "Estonia", sub: "Tallinn", tz: "Europe/Tallinn", keys: ["estonia", "tallinn"] },
  { label: "Ethiopia", sub: "Addis Ababa", tz: "Africa/Addis_Ababa", keys: ["ethiopia", "addis ababa"] },
  { label: "Finland", sub: "Helsinki", tz: "Europe/Helsinki", keys: ["finland", "helsinki"] },
  { label: "France", sub: "Paris", tz: "Europe/Paris", keys: ["france"] },
  { label: "Georgia", sub: "Tbilisi", tz: "Asia/Tbilisi", keys: ["georgia country", "tbilisi"] },
  { label: "Germany", sub: "Berlin", tz: "Europe/Berlin", keys: ["germany", "deutschland", "berlin"] },
  { label: "Ghana", sub: "Accra", tz: "Africa/Accra", keys: ["ghana", "accra"] },
  { label: "Greece", sub: "Athens", tz: "Europe/Athens", keys: ["greece", "athens"] },
  { label: "Guatemala", sub: "Guatemala City", tz: "America/Guatemala", keys: ["guatemala"] },
  { label: "Hong Kong", sub: "Hong Kong SAR", tz: "Asia/Hong_Kong", keys: ["hong kong", "hk", "hongkong"] },
  { label: "Hungary", sub: "Budapest", tz: "Europe/Budapest", keys: ["hungary", "budapest"] },
  { label: "Iceland", sub: "Reykjavik", tz: "Atlantic/Reykjavik", keys: ["iceland", "reykjavik"] },
  { label: "India", sub: "New Delhi / Mumbai / Bangalore", tz: "Asia/Kolkata", keys: ["india", "bharat", "hindustan"] },
  { label: "Indonesia (West)", sub: "Jakarta / Surabaya", tz: "Asia/Jakarta", keys: ["indonesia", "jakarta"] },
  { label: "Iran", sub: "Tehran", tz: "Asia/Tehran", keys: ["iran", "persia", "tehran"] },
  { label: "Iraq", sub: "Baghdad", tz: "Asia/Baghdad", keys: ["iraq", "baghdad"] },
  { label: "Ireland", sub: "Dublin", tz: "Europe/Dublin", keys: ["ireland", "dublin", "éire"] },
  { label: "Israel", sub: "Jerusalem / Tel Aviv", tz: "Asia/Jerusalem", keys: ["israel", "jerusalem", "tel aviv"] },
  { label: "Italy", sub: "Rome / Milan", tz: "Europe/Rome", keys: ["italy", "italia", "rome", "milan"] },
  { label: "Japan", sub: "Tokyo / Osaka", tz: "Asia/Tokyo", keys: ["japan", "nippon"] },
  { label: "Jordan", sub: "Amman", tz: "Asia/Amman", keys: ["jordan", "amman"] },
  { label: "Kazakhstan", sub: "Almaty", tz: "Asia/Almaty", keys: ["kazakhstan", "almaty"] },
  { label: "Kenya", sub: "Nairobi", tz: "Africa/Nairobi", keys: ["kenya", "nairobi"] },
  { label: "Kuwait", sub: "Kuwait City", tz: "Asia/Kuwait", keys: ["kuwait"] },
  { label: "Kyrgyzstan", sub: "Bishkek", tz: "Asia/Bishkek", keys: ["kyrgyzstan", "bishkek"] },
  { label: "Laos", sub: "Vientiane", tz: "Asia/Vientiane", keys: ["laos", "vientiane"] },
  { label: "Latvia", sub: "Riga", tz: "Europe/Riga", keys: ["latvia", "riga"] },
  { label: "Lebanon", sub: "Beirut", tz: "Asia/Beirut", keys: ["lebanon", "beirut"] },
  { label: "Libya", sub: "Tripoli", tz: "Africa/Tripoli", keys: ["libya", "tripoli"] },
  { label: "Lithuania", sub: "Vilnius", tz: "Europe/Vilnius", keys: ["lithuania", "vilnius"] },
  { label: "Luxembourg", sub: "Luxembourg City", tz: "Europe/Luxembourg", keys: ["luxembourg"] },
  { label: "Malaysia", sub: "Kuala Lumpur", tz: "Asia/Kuala_Lumpur", keys: ["malaysia", "kuala lumpur", "kl"] },
  { label: "Mexico (Central)", sub: "Mexico City / Guadalajara", tz: "America/Mexico_City", keys: ["mexico", "mexico city"] },
  { label: "Moldova", sub: "Chișinău", tz: "Europe/Chisinau", keys: ["moldova", "chisinau"] },
  { label: "Mongolia", sub: "Ulaanbaatar", tz: "Asia/Ulaanbaatar", keys: ["mongolia", "ulaanbaatar"] },
  { label: "Morocco", sub: "Casablanca", tz: "Africa/Casablanca", keys: ["morocco", "casablanca"] },
  { label: "Myanmar", sub: "Yangon", tz: "Asia/Yangon", keys: ["myanmar", "burma", "yangon", "rangoon"] },
  { label: "Nepal", sub: "Kathmandu", tz: "Asia/Kathmandu", keys: ["nepal", "kathmandu"] },
  { label: "Netherlands", sub: "Amsterdam", tz: "Europe/Amsterdam", keys: ["netherlands", "holland", "amsterdam"] },
  { label: "New Zealand", sub: "Auckland / Wellington", tz: "Pacific/Auckland", keys: ["new zealand", "aotearoa", "nz"] },
  { label: "Nigeria", sub: "Lagos / Abuja", tz: "Africa/Lagos", keys: ["nigeria", "lagos", "abuja"] },
  { label: "North Korea", sub: "Pyongyang", tz: "Asia/Pyongyang", keys: ["north korea", "pyongyang", "dprk"] },
  { label: "Norway", sub: "Oslo", tz: "Europe/Oslo", keys: ["norway", "norge", "oslo"] },
  { label: "Oman", sub: "Muscat", tz: "Asia/Muscat", keys: ["oman", "muscat"] },
  { label: "Pakistan", sub: "Karachi / Islamabad", tz: "Asia/Karachi", keys: ["pakistan", "karachi", "islamabad", "lahore"] },
  { label: "Palestine", sub: "Gaza / West Bank", tz: "Asia/Gaza", keys: ["palestine", "gaza"] },
  { label: "Panama", sub: "Panama City", tz: "America/Panama", keys: ["panama"] },
  { label: "Paraguay", sub: "Asunción", tz: "America/Asuncion", keys: ["paraguay", "asuncion", "asunción"] },
  { label: "Peru", sub: "Lima", tz: "America/Lima", keys: ["peru", "lima"] },
  { label: "Philippines", sub: "Manila", tz: "Asia/Manila", keys: ["philippines", "manila", "pilipinas"] },
  { label: "Poland", sub: "Warsaw", tz: "Europe/Warsaw", keys: ["poland", "polska", "warsaw"] },
  { label: "Portugal", sub: "Lisbon", tz: "Europe/Lisbon", keys: ["portugal", "lisbon", "lisboa"] },
  { label: "Qatar", sub: "Doha", tz: "Asia/Qatar", keys: ["qatar", "doha"] },
  { label: "Romania", sub: "Bucharest", tz: "Europe/Bucharest", keys: ["romania", "bucharest"] },
  { label: "Russia (Moscow)", sub: "Moscow / St. Petersburg", tz: "Europe/Moscow", keys: ["russia", "russia moscow", "moscow"] },
  { label: "Russia (Yekaterinburg)", sub: "Ural region", tz: "Asia/Yekaterinburg", keys: ["russia yekaterinburg", "yekaterinburg"] },
  { label: "Russia (Novosibirsk)", sub: "Siberia (central)", tz: "Asia/Novosibirsk", keys: ["russia novosibirsk", "novosibirsk", "siberia"] },
  { label: "Russia (Vladivostok)", sub: "Far East Russia", tz: "Asia/Vladivostok", keys: ["russia vladivostok", "vladivostok", "far east"] },
  { label: "Saudi Arabia", sub: "Riyadh / Jeddah / Mecca", tz: "Asia/Riyadh", keys: ["saudi arabia", "ksa", "riyadh", "jeddah", "mecca", "medina"] },
  { label: "Serbia", sub: "Belgrade", tz: "Europe/Belgrade", keys: ["serbia", "belgrade"] },
  { label: "Singapore", sub: "Singapore", tz: "Asia/Singapore", keys: ["singapore"] },
  { label: "Slovakia", sub: "Bratislava", tz: "Europe/Bratislava", keys: ["slovakia", "bratislava"] },
  { label: "Slovenia", sub: "Ljubljana", tz: "Europe/Ljubljana", keys: ["slovenia", "ljubljana"] },
  { label: "South Africa", sub: "Johannesburg / Cape Town", tz: "Africa/Johannesburg", keys: ["south africa", "johannesburg", "cape town", "durban"] },
  { label: "South Korea", sub: "Seoul / Busan", tz: "Asia/Seoul", keys: ["south korea", "korea", "seoul", "busan"] },
  { label: "Spain", sub: "Madrid / Barcelona", tz: "Europe/Madrid", keys: ["spain", "españa", "madrid", "barcelona"] },
  { label: "Sri Lanka", sub: "Colombo", tz: "Asia/Colombo", keys: ["sri lanka", "ceylon", "colombo"] },
  { label: "Sudan", sub: "Khartoum", tz: "Africa/Khartoum", keys: ["sudan", "khartoum"] },
  { label: "Sweden", sub: "Stockholm", tz: "Europe/Stockholm", keys: ["sweden", "sverige", "stockholm"] },
  { label: "Switzerland", sub: "Zurich / Geneva", tz: "Europe/Zurich", keys: ["switzerland", "schweiz", "zurich", "geneva"] },
  { label: "Syria", sub: "Damascus", tz: "Asia/Damascus", keys: ["syria", "damascus"] },
  { label: "Taiwan", sub: "Taipei", tz: "Asia/Taipei", keys: ["taiwan", "taipei", "roc"] },
  { label: "Tanzania", sub: "Dar es Salaam", tz: "Africa/Dar_es_Salaam", keys: ["tanzania", "dar es salaam"] },
  { label: "Thailand", sub: "Bangkok", tz: "Asia/Bangkok", keys: ["thailand", "siam", "bangkok"] },
  { label: "Tunisia", sub: "Tunis", tz: "Africa/Tunis", keys: ["tunisia", "tunis"] },
  { label: "Turkey", sub: "Istanbul / Ankara", tz: "Europe/Istanbul", keys: ["turkey", "türkiye", "istanbul", "ankara"] },
  { label: "UAE", sub: "Dubai / Abu Dhabi", tz: "Asia/Dubai", keys: ["uae", "united arab emirates", "dubai", "abu dhabi", "sharjah"] },
  { label: "Uganda", sub: "Kampala", tz: "Africa/Kampala", keys: ["uganda", "kampala"] },
  { label: "Ukraine", sub: "Kyiv", tz: "Europe/Kyiv", keys: ["ukraine", "kyiv", "kiev"] },
  { label: "United Kingdom", sub: "London / Manchester / Edinburgh", tz: "Europe/London", keys: ["united kingdom", "uk", "britain", "england", "scotland", "wales", "northern ireland", "london", "manchester", "birmingham", "edinburgh"] },
  { label: "USA — Eastern", sub: "New York / Washington DC / Miami", tz: "America/New_York", keys: ["united states", "usa", "us eastern", "america eastern"] },
  { label: "USA — Central", sub: "Chicago / Dallas / Houston", tz: "America/Chicago", keys: ["us central", "america central"] },
  { label: "USA — Mountain", sub: "Denver / Phoenix / Salt Lake City", tz: "America/Denver", keys: ["us mountain", "america mountain"] },
  { label: "USA — Pacific", sub: "Los Angeles / San Francisco / Seattle", tz: "America/Los_Angeles", keys: ["us pacific", "america pacific"] },
  { label: "Uruguay", sub: "Montevideo", tz: "America/Montevideo", keys: ["uruguay", "montevideo"] },
  { label: "Uzbekistan", sub: "Tashkent", tz: "Asia/Tashkent", keys: ["uzbekistan", "tashkent"] },
  { label: "Venezuela", sub: "Caracas", tz: "America/Caracas", keys: ["venezuela", "caracas"] },
  { label: "Vietnam", sub: "Hanoi / Ho Chi Minh City", tz: "Asia/Ho_Chi_Minh", keys: ["vietnam", "viet nam", "hanoi", "ho chi minh", "saigon"] },
  { label: "Zimbabwe", sub: "Harare", tz: "Africa/Harare", keys: ["zimbabwe", "harare"] },

  // ── US States ──────────────────────────────────────────────────────────────
  { label: "Alabama, US", sub: "Central Time", tz: "America/Chicago", keys: ["alabama", "montgomery", "birmingham al"] },
  { label: "Alaska, US", sub: "Alaska Time", tz: "America/Anchorage", keys: ["alaska", "anchorage", "juneau", "fairbanks"] },
  { label: "Arizona, US", sub: "Mountain Time (no DST)", tz: "America/Phoenix", keys: ["arizona", "phoenix", "tucson", "mesa"] },
  { label: "Arkansas, US", sub: "Central Time", tz: "America/Chicago", keys: ["arkansas", "little rock"] },
  { label: "California, US", sub: "Pacific Time", tz: "America/Los_Angeles", keys: ["california", "ca", "los angeles", "san francisco", "san diego", "san jose", "sacramento", "fresno", "long beach", "oakland", "bakersfield"] },
  { label: "Colorado, US", sub: "Mountain Time", tz: "America/Denver", keys: ["colorado", "denver", "colorado springs", "aurora"] },
  { label: "Connecticut, US", sub: "Eastern Time", tz: "America/New_York", keys: ["connecticut", "hartford", "new haven"] },
  { label: "Delaware, US", sub: "Eastern Time", tz: "America/New_York", keys: ["delaware", "wilmington", "dover"] },
  { label: "Florida, US", sub: "Eastern Time", tz: "America/New_York", keys: ["florida", "miami", "orlando", "tampa", "jacksonville"] },
  { label: "Georgia, US", sub: "Eastern Time", tz: "America/New_York", keys: ["georgia us", "atlanta", "savannah"] },
  { label: "Hawaii, US", sub: "Hawaii Time (no DST)", tz: "Pacific/Honolulu", keys: ["hawaii", "honolulu", "hilo", "maui"] },
  { label: "Idaho, US", sub: "Mountain Time", tz: "America/Boise", keys: ["idaho", "boise"] },
  { label: "Illinois, US", sub: "Central Time", tz: "America/Chicago", keys: ["illinois", "chicago", "springfield il"] },
  { label: "Indiana, US", sub: "Eastern Time", tz: "America/Indiana/Indianapolis", keys: ["indiana", "indianapolis"] },
  { label: "Iowa, US", sub: "Central Time", tz: "America/Chicago", keys: ["iowa", "des moines"] },
  { label: "Kansas, US", sub: "Central Time", tz: "America/Chicago", keys: ["kansas", "wichita", "kansas city ks"] },
  { label: "Kentucky, US", sub: "Eastern Time", tz: "America/Kentucky/Louisville", keys: ["kentucky", "louisville", "lexington"] },
  { label: "Louisiana, US", sub: "Central Time", tz: "America/Chicago", keys: ["louisiana", "new orleans", "baton rouge"] },
  { label: "Maine, US", sub: "Eastern Time", tz: "America/New_York", keys: ["maine", "portland me"] },
  { label: "Maryland, US", sub: "Eastern Time", tz: "America/New_York", keys: ["maryland", "baltimore", "annapolis"] },
  { label: "Massachusetts, US", sub: "Eastern Time", tz: "America/New_York", keys: ["massachusetts", "boston"] },
  { label: "Michigan, US", sub: "Eastern Time", tz: "America/Detroit", keys: ["michigan", "detroit", "grand rapids"] },
  { label: "Minnesota, US", sub: "Central Time", tz: "America/Chicago", keys: ["minnesota", "minneapolis", "saint paul"] },
  { label: "Mississippi, US", sub: "Central Time", tz: "America/Chicago", keys: ["mississippi", "jackson ms"] },
  { label: "Missouri, US", sub: "Central Time", tz: "America/Chicago", keys: ["missouri", "kansas city mo", "st. louis", "saint louis"] },
  { label: "Montana, US", sub: "Mountain Time", tz: "America/Denver", keys: ["montana", "billings", "missoula"] },
  { label: "Nebraska, US", sub: "Central Time", tz: "America/Chicago", keys: ["nebraska", "omaha", "lincoln ne"] },
  { label: "Nevada, US", sub: "Pacific Time", tz: "America/Los_Angeles", keys: ["nevada", "las vegas", "reno"] },
  { label: "New Hampshire, US", sub: "Eastern Time", tz: "America/New_York", keys: ["new hampshire", "manchester nh", "concord nh"] },
  { label: "New Jersey, US", sub: "Eastern Time", tz: "America/New_York", keys: ["new jersey", "newark", "jersey city", "trenton"] },
  { label: "New Mexico, US", sub: "Mountain Time", tz: "America/Denver", keys: ["new mexico", "albuquerque", "santa fe"] },
  { label: "New York, US", sub: "Eastern Time", tz: "America/New_York", keys: ["new york", "nyc", "new york city", "brooklyn", "queens", "manhattan", "bronx", "buffalo", "rochester ny"] },
  { label: "North Carolina, US", sub: "Eastern Time", tz: "America/New_York", keys: ["north carolina", "charlotte", "raleigh", "durham"] },
  { label: "North Dakota, US", sub: "Central Time", tz: "America/Chicago", keys: ["north dakota", "fargo", "bismarck"] },
  { label: "Ohio, US", sub: "Eastern Time", tz: "America/New_York", keys: ["ohio", "columbus", "cleveland", "cincinnati"] },
  { label: "Oklahoma, US", sub: "Central Time", tz: "America/Chicago", keys: ["oklahoma", "oklahoma city", "tulsa"] },
  { label: "Oregon, US", sub: "Pacific Time", tz: "America/Los_Angeles", keys: ["oregon", "portland or", "salem or", "eugene"] },
  { label: "Pennsylvania, US", sub: "Eastern Time", tz: "America/New_York", keys: ["pennsylvania", "philadelphia", "pittsburgh", "harrisburg"] },
  { label: "Rhode Island, US", sub: "Eastern Time", tz: "America/New_York", keys: ["rhode island", "providence"] },
  { label: "South Carolina, US", sub: "Eastern Time", tz: "America/New_York", keys: ["south carolina", "columbia sc", "charleston sc"] },
  { label: "South Dakota, US", sub: "Central Time", tz: "America/Chicago", keys: ["south dakota", "sioux falls", "pierre"] },
  { label: "Tennessee, US", sub: "Central Time", tz: "America/Chicago", keys: ["tennessee", "nashville", "memphis", "knoxville"] },
  { label: "Texas, US", sub: "Central Time", tz: "America/Chicago", keys: ["texas", "tx", "houston", "san antonio", "dallas", "austin", "fort worth", "el paso"] },
  { label: "Utah, US", sub: "Mountain Time", tz: "America/Denver", keys: ["utah", "salt lake city", "provo"] },
  { label: "Vermont, US", sub: "Eastern Time", tz: "America/New_York", keys: ["vermont", "burlington vt", "montpelier"] },
  { label: "Virginia, US", sub: "Eastern Time", tz: "America/New_York", keys: ["virginia", "virginia beach", "norfolk", "richmond va"] },
  { label: "Washington (State), US", sub: "Pacific Time", tz: "America/Los_Angeles", keys: ["washington state", "seattle", "spokane", "tacoma"] },
  { label: "West Virginia, US", sub: "Eastern Time", tz: "America/New_York", keys: ["west virginia", "charleston wv"] },
  { label: "Wisconsin, US", sub: "Central Time", tz: "America/Chicago", keys: ["wisconsin", "milwaukee", "madison wi"] },
  { label: "Wyoming, US", sub: "Mountain Time", tz: "America/Denver", keys: ["wyoming", "cheyenne"] },
  { label: "Washington DC, US", sub: "Eastern Time", tz: "America/New_York", keys: ["washington dc", "dc", "district of columbia"] },

  // ── Canadian Provinces ─────────────────────────────────────────────────────
  { label: "British Columbia, Canada", sub: "Pacific Time", tz: "America/Vancouver", keys: ["british columbia", "bc", "vancouver", "victoria bc"] },
  { label: "Alberta, Canada", sub: "Mountain Time", tz: "America/Edmonton", keys: ["alberta", "calgary", "edmonton"] },
  { label: "Saskatchewan, Canada", sub: "Central Time (no DST)", tz: "America/Regina", keys: ["saskatchewan", "regina", "saskatoon"] },
  { label: "Manitoba, Canada", sub: "Central Time", tz: "America/Winnipeg", keys: ["manitoba", "winnipeg"] },
  { label: "Ontario, Canada", sub: "Eastern Time", tz: "America/Toronto", keys: ["ontario", "toronto", "ottawa", "hamilton on", "mississauga"] },
  { label: "Quebec, Canada", sub: "Eastern Time", tz: "America/Toronto", keys: ["quebec", "québec", "montreal", "montréal", "québec city"] },
  { label: "New Brunswick, Canada", sub: "Atlantic Time", tz: "America/Moncton", keys: ["new brunswick", "moncton", "fredericton"] },
  { label: "Nova Scotia, Canada", sub: "Atlantic Time", tz: "America/Halifax", keys: ["nova scotia", "halifax"] },
  { label: "Newfoundland, Canada", sub: "Newfoundland Time", tz: "America/St_Johns", keys: ["newfoundland", "st. john's", "saint john's"] },
  { label: "PEI, Canada", sub: "Atlantic Time", tz: "America/Halifax", keys: ["prince edward island", "pei", "charlottetown"] },

  // ── Australian States ──────────────────────────────────────────────────────
  { label: "New South Wales, Australia", sub: "AEST / AEDT", tz: "Australia/Sydney", keys: ["new south wales", "nsw", "sydney", "newcastle au", "wollongong"] },
  { label: "Victoria, Australia", sub: "AEST / AEDT", tz: "Australia/Melbourne", keys: ["victoria au", "melbourne", "geelong"] },
  { label: "Queensland, Australia", sub: "AEST (no DST)", tz: "Australia/Brisbane", keys: ["queensland", "brisbane", "gold coast", "cairns"] },
  { label: "South Australia", sub: "ACST / ACDT", tz: "Australia/Adelaide", keys: ["south australia", "sa au", "adelaide"] },
  { label: "Western Australia", sub: "AWST", tz: "Australia/Perth", keys: ["western australia", "wa au", "perth"] },
  { label: "Northern Territory, Australia", sub: "ACST (no DST)", tz: "Australia/Darwin", keys: ["northern territory", "nt au", "darwin"] },
  { label: "Tasmania, Australia", sub: "AEST / AEDT", tz: "Australia/Hobart", keys: ["tasmania", "hobart"] },
  { label: "ACT, Australia", sub: "AEST / AEDT", tz: "Australia/Sydney", keys: ["act", "australian capital territory", "canberra"] },

  // ── Major Indian Cities (all same timezone) ────────────────────────────────
  { label: "Mumbai, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["mumbai", "bombay"] },
  { label: "Delhi, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["delhi", "new delhi", "ncr"] },
  { label: "Bangalore, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["bangalore", "bengaluru"] },
  { label: "Hyderabad, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["hyderabad", "cyberabad"] },
  { label: "Chennai, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["chennai", "madras"] },
  { label: "Kolkata, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["kolkata", "calcutta"] },
  { label: "Pune, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["pune", "poona"] },
  { label: "Ahmedabad, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["ahmedabad"] },
  { label: "Jaipur, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["jaipur"] },
  { label: "Lucknow, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["lucknow"] },
  { label: "Chandigarh, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["chandigarh"] },
  { label: "Goa, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["goa", "panaji"] },
  { label: "Kochi, India", sub: "IST (UTC+5:30)", tz: "Asia/Kolkata", keys: ["kochi", "cochin", "kerala"] },

  // ── Pacific / Oceania ──────────────────────────────────────────────────────
  { label: "Auckland, New Zealand", sub: "NZST / NZDT", tz: "Pacific/Auckland", keys: ["auckland"] },
  { label: "Fiji", sub: "Fiji Time", tz: "Pacific/Fiji", keys: ["fiji", "suva"] },
  { label: "Guam", sub: "Chamorro Standard Time", tz: "Pacific/Guam", keys: ["guam"] },
  { label: "Hawaii, US", sub: "HST", tz: "Pacific/Honolulu", keys: ["hawaii", "honolulu"] },

  // ── Middle East Cities ─────────────────────────────────────────────────────
  { label: "Dubai, UAE", sub: "GST (UTC+4)", tz: "Asia/Dubai", keys: ["dubai", "dxb"] },
  { label: "Abu Dhabi, UAE", sub: "GST (UTC+4)", tz: "Asia/Dubai", keys: ["abu dhabi"] },
  { label: "Riyadh, Saudi Arabia", sub: "AST (UTC+3)", tz: "Asia/Riyadh", keys: ["riyadh"] },
  { label: "Doha, Qatar", sub: "AST (UTC+3)", tz: "Asia/Qatar", keys: ["doha", "qatar"] },
  { label: "Kuwait City, Kuwait", sub: "AST (UTC+3)", tz: "Asia/Kuwait", keys: ["kuwait city", "kuwait"] },
  { label: "Muscat, Oman", sub: "GST (UTC+4)", tz: "Asia/Muscat", keys: ["muscat", "oman"] },
  { label: "Manama, Bahrain", sub: "AST (UTC+3)", tz: "Asia/Bahrain", keys: ["bahrain", "manama"] },

  // ── African Cities ─────────────────────────────────────────────────────────
  { label: "Cairo, Egypt", sub: "EET (UTC+2)", tz: "Africa/Cairo", keys: ["cairo"] },
  { label: "Lagos, Nigeria", sub: "WAT (UTC+1)", tz: "Africa/Lagos", keys: ["lagos", "abuja"] },
  { label: "Nairobi, Kenya", sub: "EAT (UTC+3)", tz: "Africa/Nairobi", keys: ["nairobi"] },
  { label: "Johannesburg, South Africa", sub: "SAST (UTC+2)", tz: "Africa/Johannesburg", keys: ["johannesburg", "joburg", "jozi", "pretoria", "cape town"] },
  { label: "Addis Ababa, Ethiopia", sub: "EAT (UTC+3)", tz: "Africa/Addis_Ababa", keys: ["addis ababa", "ethiopia"] },
  { label: "Accra, Ghana", sub: "GMT (UTC+0)", tz: "Africa/Accra", keys: ["accra", "ghana"] },
  { label: "Casablanca, Morocco", sub: "WET (UTC+0/+1)", tz: "Africa/Casablanca", keys: ["casablanca", "rabat"] },
  { label: "Dar es Salaam, Tanzania", sub: "EAT (UTC+3)", tz: "Africa/Dar_es_Salaam", keys: ["dar es salaam", "tanzania"] },
  { label: "Kampala, Uganda", sub: "EAT (UTC+3)", tz: "Africa/Kampala", keys: ["kampala", "uganda"] },
  { label: "Khartoum, Sudan", sub: "EAT (UTC+3)", tz: "Africa/Khartoum", keys: ["khartoum"] },
  { label: "Tunis, Tunisia", sub: "CET (UTC+1)", tz: "Africa/Tunis", keys: ["tunis", "tunisia"] },

  // ── European Cities ────────────────────────────────────────────────────────
  { label: "London, UK", sub: "GMT / BST", tz: "Europe/London", keys: ["london"] },
  { label: "Paris, France", sub: "CET / CEST", tz: "Europe/Paris", keys: ["paris"] },
  { label: "Berlin, Germany", sub: "CET / CEST", tz: "Europe/Berlin", keys: ["berlin", "munich", "hamburg", "cologne", "frankfurt"] },
  { label: "Amsterdam, Netherlands", sub: "CET / CEST", tz: "Europe/Amsterdam", keys: ["amsterdam"] },
  { label: "Brussels, Belgium", sub: "CET / CEST", tz: "Europe/Brussels", keys: ["brussels", "bruxelles"] },
  { label: "Zurich, Switzerland", sub: "CET / CEST", tz: "Europe/Zurich", keys: ["zurich", "zürich", "geneva", "bern"] },
  { label: "Vienna, Austria", sub: "CET / CEST", tz: "Europe/Vienna", keys: ["vienna", "wien"] },
  { label: "Rome, Italy", sub: "CET / CEST", tz: "Europe/Rome", keys: ["rome", "roma", "milan", "naples", "turin", "venice"] },
  { label: "Madrid, Spain", sub: "CET / CEST", tz: "Europe/Madrid", keys: ["madrid", "barcelona", "valencia", "seville", "bilbao"] },
  { label: "Lisbon, Portugal", sub: "WET / WEST", tz: "Europe/Lisbon", keys: ["lisbon", "lisboa", "porto"] },
  { label: "Stockholm, Sweden", sub: "CET / CEST", tz: "Europe/Stockholm", keys: ["stockholm", "gothenburg", "malmo"] },
  { label: "Oslo, Norway", sub: "CET / CEST", tz: "Europe/Oslo", keys: ["oslo"] },
  { label: "Copenhagen, Denmark", sub: "CET / CEST", tz: "Europe/Copenhagen", keys: ["copenhagen", "kobenhavn"] },
  { label: "Helsinki, Finland", sub: "EET / EEST", tz: "Europe/Helsinki", keys: ["helsinki"] },
  { label: "Warsaw, Poland", sub: "CET / CEST", tz: "Europe/Warsaw", keys: ["warsaw", "warszawa", "krakow"] },
  { label: "Prague, Czech Republic", sub: "CET / CEST", tz: "Europe/Prague", keys: ["prague", "praha"] },
  { label: "Budapest, Hungary", sub: "CET / CEST", tz: "Europe/Budapest", keys: ["budapest"] },
  { label: "Bucharest, Romania", sub: "EET / EEST", tz: "Europe/Bucharest", keys: ["bucharest", "bucuresti"] },
  { label: "Athens, Greece", sub: "EET / EEST", tz: "Europe/Athens", keys: ["athens", "athina"] },
  { label: "Sofia, Bulgaria", sub: "EET / EEST", tz: "Europe/Sofia", keys: ["sofia"] },
  { label: "Kyiv, Ukraine", sub: "EET / EEST", tz: "Europe/Kyiv", keys: ["kyiv", "kiev"] },
  { label: "Moscow, Russia", sub: "MSK (UTC+3)", tz: "Europe/Moscow", keys: ["moscow", "moskva", "st. petersburg", "saint petersburg"] },
  { label: "Istanbul, Turkey", sub: "TRT (UTC+3)", tz: "Europe/Istanbul", keys: ["istanbul", "ankara", "izmir"] },
  { label: "Dublin, Ireland", sub: "GMT / IST", tz: "Europe/Dublin", keys: ["dublin", "cork", "galway"] },
  { label: "Reykjavik, Iceland", sub: "GMT (UTC+0, no DST)", tz: "Atlantic/Reykjavik", keys: ["reykjavik", "iceland"] },
  { label: "Belgrade, Serbia", sub: "CET / CEST", tz: "Europe/Belgrade", keys: ["belgrade", "beograd"] },
  { label: "Zagreb, Croatia", sub: "CET / CEST", tz: "Europe/Zagreb", keys: ["zagreb"] },
  { label: "Riga, Latvia", sub: "EET / EEST", tz: "Europe/Riga", keys: ["riga"] },
  { label: "Tallinn, Estonia", sub: "EET / EEST", tz: "Europe/Tallinn", keys: ["tallinn"] },
  { label: "Vilnius, Lithuania", sub: "EET / EEST", tz: "Europe/Vilnius", keys: ["vilnius"] },
  { label: "Minsk, Belarus", sub: "FET (UTC+3)", tz: "Europe/Minsk", keys: ["minsk"] },

  // ── Americas (other cities) ────────────────────────────────────────────────
  { label: "New York City, US", sub: "Eastern Time", tz: "America/New_York", keys: ["new york", "nyc", "manhattan", "brooklyn"] },
  { label: "Los Angeles, US", sub: "Pacific Time", tz: "America/Los_Angeles", keys: ["los angeles", "la", "hollywood", "santa monica"] },
  { label: "Chicago, US", sub: "Central Time", tz: "America/Chicago", keys: ["chicago"] },
  { label: "Houston, US", sub: "Central Time", tz: "America/Chicago", keys: ["houston"] },
  { label: "Phoenix, US", sub: "Mountain Time (no DST)", tz: "America/Phoenix", keys: ["phoenix"] },
  { label: "Philadelphia, US", sub: "Eastern Time", tz: "America/New_York", keys: ["philadelphia", "philly"] },
  { label: "San Antonio, US", sub: "Central Time", tz: "America/Chicago", keys: ["san antonio"] },
  { label: "Dallas, US", sub: "Central Time", tz: "America/Chicago", keys: ["dallas", "fort worth"] },
  { label: "San Francisco, US", sub: "Pacific Time", tz: "America/Los_Angeles", keys: ["san francisco", "sf", "bay area", "silicon valley", "san jose"] },
  { label: "Seattle, US", sub: "Pacific Time", tz: "America/Los_Angeles", keys: ["seattle"] },
  { label: "Denver, US", sub: "Mountain Time", tz: "America/Denver", keys: ["denver"] },
  { label: "Boston, US", sub: "Eastern Time", tz: "America/New_York", keys: ["boston"] },
  { label: "Atlanta, US", sub: "Eastern Time", tz: "America/New_York", keys: ["atlanta"] },
  { label: "Miami, US", sub: "Eastern Time", tz: "America/New_York", keys: ["miami"] },
  { label: "Las Vegas, US", sub: "Pacific Time", tz: "America/Los_Angeles", keys: ["las vegas", "vegas"] },
  { label: "Toronto, Canada", sub: "Eastern Time", tz: "America/Toronto", keys: ["toronto"] },
  { label: "Vancouver, Canada", sub: "Pacific Time", tz: "America/Vancouver", keys: ["vancouver"] },
  { label: "Montreal, Canada", sub: "Eastern Time", tz: "America/Toronto", keys: ["montreal", "montréal"] },
  { label: "Calgary, Canada", sub: "Mountain Time", tz: "America/Edmonton", keys: ["calgary"] },
  { label: "Ottawa, Canada", sub: "Eastern Time", tz: "America/Toronto", keys: ["ottawa"] },
  { label: "Mexico City, Mexico", sub: "CST / CDT", tz: "America/Mexico_City", keys: ["mexico city", "cdmx"] },
  { label: "São Paulo, Brazil", sub: "BRT (UTC-3)", tz: "America/Sao_Paulo", keys: ["sao paulo", "são paulo"] },
  { label: "Rio de Janeiro, Brazil", sub: "BRT (UTC-3)", tz: "America/Sao_Paulo", keys: ["rio de janeiro", "rio"] },
  { label: "Buenos Aires, Argentina", sub: "ART (UTC-3)", tz: "America/Argentina/Buenos_Aires", keys: ["buenos aires"] },
  { label: "Lima, Peru", sub: "PET (UTC-5)", tz: "America/Lima", keys: ["lima"] },
  { label: "Bogotá, Colombia", sub: "COT (UTC-5)", tz: "America/Bogota", keys: ["bogota", "bogotá"] },
  { label: "Santiago, Chile", sub: "CLT / CLST", tz: "America/Santiago", keys: ["santiago"] },
  { label: "Havana, Cuba", sub: "CST / CDT", tz: "America/Havana", keys: ["havana", "la habana"] },
  { label: "San Juan, Puerto Rico", sub: "AST (UTC-4)", tz: "America/Puerto_Rico", keys: ["san juan", "puerto rico"] },
  { label: "Anchorage, Alaska", sub: "AKST / AKDT", tz: "America/Anchorage", keys: ["anchorage"] },
  { label: "Honolulu, Hawaii", sub: "HST (UTC-10)", tz: "Pacific/Honolulu", keys: ["honolulu", "oahu"] },
];

export function searchTZ(
  query: string,
  ianaZones: string[]
): TZEntry[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];

  const seen = new Set<string>();
  const results: TZEntry[] = [];

  // Short queries (≤5 chars) are likely abbreviations — e.g. "EST", "IST", "AEST".
  // Use word-start matching so "est" does NOT match "w[est]ern" or "c[est]".
  // Long queries use full substring matching.
  const isShort = q.length <= 5;

  const hits = (text: string) =>
    isShort
      ? text.split(/[\s\-\/]+/).some((w) => w.startsWith(q))
      : text.includes(q);

  for (const entry of TZ_DATA) {
    if (seen.has(entry.tz)) continue;
    const match =
      hits(entry.label.toLowerCase()) ||
      hits(entry.sub.toLowerCase()) ||
      entry.keys.some((k) => hits(k));
    if (match) {
      seen.add(entry.tz);
      results.push(entry);
    }
  }

  // IANA fallback — catches obscure zones not in the curated list.
  // For short queries use word-start on each path segment to avoid "EST" matching "Australia/West".
  for (const tz of ianaZones) {
    if (seen.has(tz)) continue;
    const tzNorm = tz.toLowerCase().replace(/_/g, " ");
    const match = isShort
      ? tzNorm.split(/[\/\s]+/).some((seg) => seg.startsWith(q))
      : tzNorm.includes(q);
    if (match) {
      const parts = tz.split("/");
      seen.add(tz);
      results.push({
        label: parts[parts.length - 1].replace(/_/g, " "),
        sub: tz,
        tz,
        keys: [],
      });
    }
  }

  return results.slice(0, 60);
}
